service: default
runtime: go113

main: go/cmd/server

instance_class: F1
automatic_scaling:
    max_instances: 1

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
