service: default
runtime: go113

main: go/cmd/server

instance_class: F1
automatic_scaling:
    max_instances: 1

handlers:
  - url: /$
    static_files: public/index.html
    upload: public/index.html

  - url: /static
    static_dir: public

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto