FROM balenalib/%%BALENA_MACHINE_NAME%%-golang:latest-build AS build

WORKDIR /go/src/github.com/powersjcb/monitor

COPY /go.mod ./
COPY /go.sum ./
RUN go get

COPY /go ./go
RUN go build -o client ./go/cmd/server/main.go

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch

COPY --from=build /go/src/github.com/powersjcb/monitor/client .

CMD ./client