FROM balenalib/%%BALENA_MACHINE_NAME%%-golang:latest-build AS build

WORKDIR /go/src/github.com/powersjcb/monitor

COPY /app ./

RUN go build go/src/cmd/client/main.go -o ./client

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch

COPY --from=build /go/src/github.com/powersjcb/monitor/client .

CMD ./client