// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	GetMetrics(ctx context.Context) ([]string, error)
	MetricForSource(ctx context.Context, source string) ([]Metric, error)
	MetricStatsPerPeriod(ctx context.Context, seconds int32) ([]MetricStatsPerPeriodRow, error)
}

var _ Querier = (*Queries)(nil)
