// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Metric struct {
	Source     string          `json:"source"`
	Ts         sql.NullTime    `json:"ts"`
	InsertedAt time.Time       `json:"inserted_at"`
	Name       string          `json:"name"`
	Target     string          `json:"target"`
	Value      sql.NullFloat64 `json:"value"`
}
