// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	GetAccountByID(ctx context.Context, id int64) (Account, error)
	GetAccountByProviderID(ctx context.Context, arg GetAccountByProviderIDParams) (Account, error)
	GetAccountIDForAPIKey(ctx context.Context, apiKey string) (int64, error)
	GetMetricStatsPerPeriod(ctx context.Context, arg GetMetricStatsPerPeriodParams) ([]GetMetricStatsPerPeriodRow, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error)
	InsertMetric(ctx context.Context, arg InsertMetricParams) (Metric, error)
}

var _ Querier = (*Queries)(nil)
