name: Monitor CI Pipeline
on: [push]

jobs:
  build:
    name: build
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - run: go build ./go/cmd/server/main.go
      - run: go build ./go/cmd/client/main.go
