name: Deploy
on:
  push:
    branches: [master]

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup and configure gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_DEPLOY_KEY_DATA }}

      # Deploy App to App Engine
      - name: Deploy App
        run: gcloud app deploy app.yaml -q

      - name: Deploy cron
        run: gcloud app deploy cron.yaml -q